config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'sign_up', to: 'users#new'
  post 'sign_up', to: 'users#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
	    @user = User.new(params[:user])
	    if @user.save
	      flash[:notice] = "You signed up successfully"
	      flash[:color]= "valid"
	    else
	      flash[:notice] = "Form is invalid"
	      flash[:color]= "invalid"
	    end
	    render "new"
	 end

	private
	def form_params
	  params.require(:user).permit(:username, :email, :firstname, :lastname, :phone, :hobby[], :gender, :status, :password_salt, :password_hash, :profile_photo)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!-- inside app/views/welcome/index.html.erb -->  
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <h5 class="text-white h4">Collapsed content</h5>
    <span class="text-muted">Toggleable via the navbar brand.</span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

<main>
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Album example</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
  <%= form_with model: @user, url: sign_up_path do |f| %>
  <div class="field">
    <p>
      <%= f.label 'Email' %><br>
      <%= f.email_field :email %>
    </p>
  </div>

  <div class="field">
    <p>
      <%= f.label 'First Name' %><br>
      <%= f.text_field :firstname %>
    </p>
  </div>

  <div class="field">
    <p>
      <%= f.label 'Last Name' %><br>
      <%= f.text_field :lastname %>
    </p>
  </div>

  <div class="field">
    <p>
      <%= f.label 'Username' %><br>
      <%= f.text_field :username %>
    </p>
  </div>

  <div class="field">
    <p>
      <%= f.label 'Phone' %><br>
      <%= f.telephone_field :phone %>
    </p>
  </div>

  <div class="field">
    <p>
      <%= f.label 'Select Gender' %><br>
      <%= f.radio_button :gender, 'male' %> Male<br />
      <%= f.radio_button :gender, 'female' %> Female<br />
      <%= f.radio_button :gender, 'others' %> others<br />
    </p>
  </div>

  <div class="field">
    <p>
      <%= f.label 'Select Hobby' %><br>
      <% days = ['Singing', 'Dancing', 'Reading', 'Cricket', 'Traveling', 'Sleeping', 'Painting']%>
      <% days.each do |day|%>
        <%=f.check_box :hobby, { multiple: true }, day, false%><%= f.label day%>
      <%end%>
    </p>
  </div>

  <div class="field">
    <p>
      <%= f.label 'Profile Photo' %><br>
      <%= f.file_field :profile_photo %>
    </p>
  </div>

  <div class="field">
    <p>
      <%= f.label 'password' %><br>
      <%= f.password_field :password %>
    </p>
  </div>

  <div class="field">
    <p>
      <%= f.label 'password_confirmation' %><br>
      <%= f.password_field :password_confirmation %>
    </p>
  </div>
   <div class="submit">
     <p>
       <%= f.submit 'Sign Up' %>
     </p>
   </div>
  <% end %>

<script type="text/javascript">

$("input[type='radio']").change(function(){ 
    if ($('input[type="radio"]:checked').val() == "others")
    {
        $('input[type="hidden"]').val('')   
        $('input[type="hidden"]').prop("type", "text");
    }
    else if ($('input[type="radio"]:checked').val() != "others")
    {
        $('input[type="hidden"]').prop("type", "hidden");
        $('input[type="hidden"]').val($('input[type="radio"]:checked').val())
    } 
});

</script>